# This is a basic workflow to help you get started with Actions

- name: floral_KSUNEXT_SUSFS
  uses: dabao1955/kernel_build_action@v1.8.3
# Controls when the workflow will run
on:
  workflow_dispatch:

jobs:
  Free-Space:
    uses: fcbg-platforms/increase-disk-space@v0.1.0
  with:
    dotnet: true
    old-dotnet: true
    haskell: true
    large-packages: true

  Build-Kernel:
    strategy:
      fail-fast: true
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Build Kernel
        uses: dabao1955/kernel_build_action@main
        with:
          kernel-url: https://android.googlesource.com/kernel/msm/+/refs/heads/android-msm-coral-4.14-android13
          kernel-dir: coral-msm-4.14
          config: floral_defconfig
          arch: arm64
          aosp-gcc: true
          aosp-clang: true
          ksu: true
          ksu-version: v0.9.5
          lxc: true
          lxc-patch: true
          nethunter: true
          nethunter-patch: true
          android-version: 13
          aosp-clang-version: r416183b1
          disable-lto: false
          anykernel3: true
